---
micronaut:
  application:
    name: cadastraldatadisposal

---
micronaut:
  io:
    watch:
      paths: src/main
      restart: true
      
---
app:
  awsAccessKey: ${awsAccessKey}  
  awsSecretKey: ${awsSecretKey}
  dataServiceUrl: ${dataServiceUrl:`https://geo.so.ch/api/data/v1/ch.so.agi.av.nachfuehrungsgemeinden.data/`}
  pdfMapUrl: ${pdfMapUrl:`https://geo.so.ch/map?hp=ch.so.agi.gemeindegrenzen&hf=%5B%5B%22bfs_gemeindenummer%22%2C%22%3D%22%2C%22{{BFS_NR}}%22%5D%5D`}
  s3BaseUrl: ${s3BaseUrl:`https://s3.eu-central-1.amazonaws.com/`}
  itfsoBucketName: ${itfsoBucketName:ch.so.agi.av.dm01avso24lv95}
  itfchBucketName: ${itfchBucketName:ch.so.agi.av.dm01avch24lv95d}
  dxfBucketName: ${dxfBucketName:ch.so.agi.av.dxfgeobau}
  shpUrl: ${shpUrl:`https://geodienste.ch/downloads/av`}
  
my:
  engine:
    cylinders: 9
  